#!/bin/sh -e
# This is the expected entry point for Cockpit CI; will be called without
# arguments but with an appropriate $TEST_OS, and optionally $TEST_SCENARIO

if [ -n "${TEST_SCENARIO}" ]; then
    export TEST_BROWSER="$TEST_SCENARIO"
fi

make check
