#!/bin/sh
# image-customize script to enable cockpit in test VMs
# The application RPM will be installed separately
set -eux

# Allow cockpit port (9090) in INPUT chain
# Do not reload firewall rule during image generation
if type firewall-cmd >/dev/null 2>&1; then
    firewall-cmd --add-service=cockpit --permanent
fi

# Install nodejs if it does not exist
if grep -isq fedora /etc/redhat-release; then
    command -v node > /dev/null 2>&1 || dnf module install -y nodejs:10
else
    command -v node > /dev/null 2>&1 || $(command -v dnf || command -v yum) install -y nodejs
fi

# disable https in cockpit and use http instead
printf "[WebService]\\nAllowUnencrypted=true\\n" > /etc/cockpit/cockpit.conf

# disable session timeout as some tests wait for too long
printf "[Session]\\nIdleTimeout=0\\n" >> /etc/cockpit/cockpit.conf

# Make cockpit.socket auto-start when system started
# Do not start it during image generation
systemctl enable cockpit.socket

# Start osbuild-composer to init its db, but do not "enable" it
# Tests expect the service to not run, it checks the "start service" button
systemctl start osbuild-composer

# TODO temporary until osbuild-composer depends on one worker
systemctl start osbuild-worker@1

# wait for lorax-composer initialization before running test
until curl --unix-socket /run/weldr/api.socket http://localhost/api/status; do
sleep 1;
done;
