#!/usr/bin/python3

import time
import composerlib
import testlib


@testlib.nondestructive
@testlib.no_retry_when_changed
class TestImageWizard(composerlib.ComposerCase):

    def testCreateQCOW2(self):
        b = self.browser

        self.login_and_go("/composer", superuser=True)
        b.wait_visible("#main")

        # Create blueprint
        b.click("tr[data-testid=httpd-server] button[aria-label='Create image']")
        b.wait_in_text(".pf-c-wizard__main", "httpd-server")
        time.sleep(1)
        # select qcow2 image type and keep default size
        b.select_PF4("#image-output-select-toggle", "QEMU Image (.qcow2)")
        b.click("button:contains('Next')")

        b.wait_in_text("#review-list", "Blueprint name")
        b.wait_in_text("#review-list", "httpd-server")
        b.wait_in_text("#review-list", "Output type")
        b.wait_in_text("#review-list", "qcow2")
        b.wait_in_text("#review-list", "Image size")
        b.wait_in_text("#review-list", "2")

        # Create image
        b.click("footer button:contains('Create')")


if __name__ == '__main__':
    testlib.test_main()
