#!/usr/bin/python3

import composerlib
import testlib


@testlib.nondestructive
@testlib.no_retry_when_changed
class TestBlueprintWizard(composerlib.ComposerCase):

    def testCreateAndDeleteBlueprint(self):
        b = self.browser

        self.login_and_go("/composer", superuser=True)
        b.wait_visible("#main")

        b.click("button:contains('Create blueprint')")
        b.wait_in_text(".pf-c-wizard__header", "Create blueprint")

        b.set_input_text("input[id='blueprint.name']", "testName")
        b.set_input_text("input[id='blueprint.description']", "testDescription")
        # go to next page
        b.click("button:contains('Next')")

        b.wait_text("h1", "Packages")
        # select openssh-server
        b.set_input_text("div[data-testid='search-available-pkgs-input'] input", "openssh-server")
        b.click("button[aria-label='Search button for available packages']")
        with b.wait_timeout(360):
            b.click("li[data-testid='openssh-server']")
            b.click("button[aria-label='Add selected']")
        # go to next page
        b.click("button:contains('Next')")

        # start of customizations
        b.wait_text("h1", "System")
        b.set_input_text("input[id='customizations.hostname']", "testHost")
        b.set_input_text("input[id='customizations.installation_device']", "/dev/sda1")
        # go to next page
        b.click("button:contains('Next')")

        b.wait_text("h1", "Users")
        b.click("button:contains('Add user')")
        b.set_input_text("input[id='customizations.user[0].name']", "admin")
        b.set_input_text("input[id='customizations.user[0].password']", "foobar")
        b.set_input_text("textarea[id='customizations.user[0].key']", "ssh-rsa key")
        b.click("input[id='customizations.user[0].isAdmin']")
        # go to next page
        b.click("button:contains('Next')")

        b.wait_text("h1", "FIDO device onboarding")
        b.set_input_text("input[id='customizations.fdo.manufacturing_server_url']", "https://test.com")
        b.set_input_text("input[id='customizations.fdo.diun_pub_key_insecure']", "keyInsecure")
        b.set_input_text("input[id='customizations.fdo.diun_pub_key_hash']", "keyHash")
        b.set_input_text("input[id='customizations.fdo.diun_pub_key_root_certs']", "rootCerts")
        # go to next page
        b.click("button:contains('Next')")

        b.wait_text("h1", "Review")
        b.click(".pf-c-wizard__footer button:contains('Create')")
        # verify that blueprint was created
        b.is_present("tr[data-testid='testName']")

        # delete blueprint
        b.click("tr[data-testid='testName'] button:contains('Delete')")
        b.is_visible("div[id='modal-delete-blueprint']")
        b.click("footer button:contains('Delete')")
        b.wait_not_present("tr[data-testid='testName']")


if __name__ == '__main__':
    testlib.test_main()
