---
# yamllint disable rule:line-length
sudo: required
dist: xenial
services:
  - docker
language: python
python:
  - "3.7"
cache:
  directories:
    - node_modules
before_install:
  - |
        git config --global user.email "travis@welder.web"
        git config --global user.name "Travis CI"
        git remote add welder https://github.com/${TRAVIS_REPO_SLUG}.git
        git fetch welder $TRAVIS_BRANCH
        git log -1 --pretty=format:%H welder/${TRAVIS_BRANCH}
        git rebase welder/${TRAVIS_BRANCH}
  - |
        if [ "$COMMAND" == "eslint" ] || [ "$COMMAND" == "stylelint" ]; then
            nvm install 'lts/*'
            nvm use 'lts/*'
        fi
install:
  - |
        if [ "$COMMAND" == "eslint" ] || [ "$COMMAND" == "stylelint" ]; then
            npm install
        fi
  - |
        if [ "$COMMAND" == "flake8" ]; then
            python -V
            pip -V
            pip install flake8
        fi
env:
  matrix:
    - COMMAND=eslint
    - COMMAND=stylelint
    - COMMAND=test_rpmbuild
    - COMMAND=flake8
script:
  - make "$COMMAND"
notifications:
  email:
    on_failure: change
    on_success: never
