---
# yamllint disable rule:line-length
sudo: required
dist: xenial
services:
  - docker
language: node_js
node_js:
  - 'lts/*'
cache:
  directories:
    - node_modules
before_install:
  - |
        git config --global user.email "travis@welder.web"
        git config --global user.name "Travis CI"
        git remote add welder https://github.com/${TRAVIS_REPO_SLUG}.git
        git fetch welder $TRAVIS_BRANCH
        git log -1 --pretty=format:%H welder/${TRAVIS_BRANCH}
        git rebase welder/${TRAVIS_BRANCH}
install:
  - |
        if [ "$COMMAND" != "test_rpmbuild" ]; then
            npm install
        fi
env:
  matrix:
    - COMMAND=eslint
    - COMMAND=stylelint
    - COMMAND=test_rpmbuild
script:
  - make "$COMMAND"
notifications:
  email:
    on_failure: change
    on_success: never
