sudo: required
dist: trusty
services:
  - docker
language: node_js
node_js:
  - "6"
cache:
  directories:
  - node_modules # NPM packages
before_install:
  - npm install
  - node run build
env:
  - COMMAND=eslint
  - COMMAND=stylelint
  - COMMAND=unit-test
  - COMMAND=end-to-end-test
script:
  - make "$COMMAND"
after_success:
  - if [ "$COMMAND" == "unit-test" ]; then npm install coveralls && cat ./coverage/lcov.info | coveralls; fi
notifications:
  email:
    on_failure: change
    on_success: change
