FROM centos:7
MAINTAINER Xiaofeng Wang <xiaofwan@redhat.com>

RUN yum install -y cockpit-ws cockpit-kubernetes && \
    yum clean all && \
    rm -rf /usr/share/cockpit/kubernetes/
RUN echo $'[Negotiate]\nCommand = /usr/libexec/cockpit-stub\n[WebService]\nShell = /shell/simple.html' > /etc/cockpit/cockpit.conf

COPY welder-web*.rpm /tmp/
RUN yum -y install /tmp/welder-web*.rpm && rm -f /tmp/welder-web*.rpm

CMD ["/usr/libexec/cockpit-ws", "--no-tls"]
EXPOSE 9090
