FROM fedora:latest
LABEL maintainer="Alexander Todorov" \
      email="atodorov@redhat.com" \
      baseimage="Fedora:latest" \
      description="A metadata db generator container running on Fedora"

RUN dnf -y install sqlite ostree sudo gobject-introspection

COPY ./import-metadata.sh /tmp/
CMD ["/tmp/import-metadata.sh"]
