FROM fedora:latest
MAINTAINER Xiaofeng Wang <xiaofwan@redhat.com>

RUN dnf install -y cockpit-ws cockpit-kubernetes && dnf clean all
RUN echo $'[Negotiate]\nCommand = /usr/libexec/cockpit-stub\n[WebService]\nShell = /shell/simple.html' > /etc/cockpit/cockpit.conf
RUN rm -rf /usr/share/cockpit/kubernetes/

CMD ["/usr/libexec/cockpit-ws", "--no-tls"]
EXPOSE 9090
