upstream_project_url: https://github.com/osbuild/cockpit-composer
specfile_path: cockpit-composer.spec
upstream_package_name: cockpit-composer
downstream_package_name: cockpit-composer
# use the nicely formatted release description from our upstream release, instead of git shortlog
copy_upstream_release_description: true

actions:
  post-upstream-clone: make spec
  create-archive: make dist-gzip

srpm_build_deps:
  - make
  - npm

jobs:
  - job: copr_build
    trigger: pull_request
    targets: &build_targets
      - centos-stream-9
      - centos-stream-10
      - fedora-all

  - job: copr_build
    trigger: commit
    branch: "^main$"
    owner: "@osbuild"
    project: "cockpit-composer-main"
    preserve_project: True
    targets: *build_targets

  - job: copr_build
    trigger: release
    owner: "@osbuild"
    project: "cockpit-composer"
    preserve_project: True
    targets: *build_targets
    actions:
      # same as the global one, but specifying actions: does not inherit
      post-upstream-clone: make spec
      create-archive:
        - sh -exc "curl -L -O https://github.com/osbuild/cockpit-composer/releases/download/${PACKIT_PROJECT_VERSION}/${PACKIT_PROJECT_NAME_VERSION}.tar.xz"
        - sh -exc "ls ${PACKIT_PROJECT_NAME_VERSION}.tar.xz"

  - job: propose_downstream
    trigger: release
    dist_git_branches:
      - fedora-all

  - job: koji_build
    trigger: commit
    dist_git_branches:
      - fedora-all

  - job: bodhi_update
    trigger: commit
    dist_git_branches:
      # rawhide updates are created automatically
      - fedora-branched
