name: Check translations source

on: [pull_request]

jobs:
  check-translations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Check source file has been generated
        run: |
          npm i
          npm run translations:extract
          if [ -n "$(git status --porcelain)" ]; then
            echo
            echo "translations/en.json needs to be generated"
            echo "Please run `npm run translations:extract`"
            exit "1"
          else
            exit "0"
          fi
