name: release
on:
  push:
    tags:
      # this is a glob, not a regexp
      - '[0-9]*'
jobs:
  source:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/cockpit-project/tasks:latest
      options: --user root
    permissions:
      # create GitHub release
      contents: write
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Workaround for https://github.com/actions/checkout/pull/697
        run: |
          git config --global --add safe.directory /__w/cockpit-composer/cockpit-composer
          git fetch --force origin $(git describe --tags):refs/tags/$(git describe --tags)

      # HACK: the clean plugin doesn't like to build in the mounted $HOME volume
      - name: Build release
        run: |
          orig=$(pwd)
          cp -r . /tmp/checkout
          cd /tmp/checkout
          make dist-gzip
          cp cockpit-composer-*.tar.gz $orig

      - name: Publish GitHub release
        uses: cockpit-project/action-release@88d994da62d1451c7073e26748c18413fcdf46e9
        with:
          filename: "cockpit-composer-${{ github.ref_name }}.tar.gz"
