name: rpm-build

on: [pull_request]

jobs:
  rpm-build:
    runs-on: ubuntu-20.04
    container:
      image: quay.io/fedora/fedora:33-x86_64

    steps:
      - name: Install Dependencies
        run: dnf install -y make cmake rpm-build which gnupg git tar xz rsync curl jq nodejs python gcc gcc-c++ libappstream-glib

      - uses: actions/checkout@v2

      - name: Run rpm-build test
        run: make rpm srpm
